### ISSUE TITLE
[Add Observation] Select One and Select Multiple forms missing space between selection elements and option labels

### ISSUE THREAD

**Issue by mmisim** [google/ground-platform#747] opened 2021-06-01 22:42 UTC
**Describe the bug**
The forms for the Select One and Select Multiple question types are missing space between the end of the option labels and the radio button/checkbox or the next option. 

**To Reproduce**
1. Add a Select One or Select Multiple question with at least two options to a layer.
2. Add an observation to a feature on the layer.

**Expected behavior**
There should be a space between the option label text and the following radio button or checkbox.

**Screenshots**
![select_one](https://user-images.githubusercontent.com/7281548/120398948-218ddf80-c309-11eb-8cb0-e661dfd0d3ef.png)
![select_multiple](https://user-images.githubusercontent.com/7281548/120398954-23f03980-c309-11eb-9628-64b32a2a1d08.png)

**Comment by gino-m** [comment] 2021-06-02 14:25
Duplicate of #375. @mmisim @scolsen  Could you "thumbs up" that issue instead?

**Closed by gino-m** 2021-06-02 14:25 UTC
Labels: type: bug
