### ISSUE TITLE
[Map] Indeterministic behavior when duplicating layers

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#746] opened 2021-06-01 21:03 UTC
**Describe the bug**
When you duplicate a layer (giving the copy a distinct color) and upload the same JSON to both the original layer and the copy, the ordering of the layer polygons is not deterministic. In the images below, both layers named "Plots" use the same underlying GeoJson

<img width="1920" alt="Screen Shot 2021-06-01 at 4 59 36 PM" src="https://user-images.githubusercontent.com/11237600/120389872-ff8d6080-c2fa-11eb-8a2f-7525f7c968a1.png">
<img width="1917" alt="Screen Shot 2021-06-01 at 5 02 15 PM" src="https://user-images.githubusercontent.com/11237600/120389974-23e93d00-c2fb-11eb-8056-3dca8fab38f8.png">

**Comment by gino-m** [comment] 2021-06-01 21:15
Duplicate of #310. Thanks for filing!

**Closed by gino-m** 2021-06-01 21:15 UTC
Labels: type: bug
