### ISSUE TITLE
[Edit task] Support conditional multiple choice questions

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1201] opened 2023-10-04 16:27 UTC
The user can add one of two conditions:

- [ ] Based on previous answer (e.g., show/hide follow up questions if user selected "Forest" for first question)
- [ ] Only show when adding a new LOI <-- @vittorino What would this look like?

See also https://github.com/google/ground-android/issues/1955

Entry point:
<img width="497" alt="image" src="https://github.com/google/ground-platform/assets/228050/60ef419d-4574-4fd7-8f11-d7384afb0614">

While editing the condition:
<img width="804" alt="image" src="https://github.com/google/ground-platform/assets/228050/b6a7cd71-3783-4437-800d-a23b346c6da3">

Once applied (on blur):
<img width="646" alt="image" src="https://github.com/google/ground-platform/assets/228050/48773273-c78a-4d2f-aca9-35d71253731e">

@vittorino A few follow-ups on Figma for next time.

**Comment by jcqli** [comment] 2024-03-08 16:12
Duplicate of https://github.com/google/ground-platform/issues/1478

**Closed by jcqli** 2024-03-08 16:12 UTC
Labels: type: fr, web, ux needed
