### ISSUE TITLE
[Terra Bio] User profile picture doesn't display 

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#732] opened 2021-06-01 19:53 UTC
**Describe the bug**
The user's google profile picture displays as a broken image in the ground web app:

<img width="359" alt="Screen Shot 2021-06-01 at 3 51 54 PM" src="https://user-images.githubusercontent.com/11237600/120382297-7887ba80-c2f1-11eb-95de-67f09cd1590e.png">

**Comment by coreyleamon** [comment] 2021-06-01 20:11
Confirmed for me as well

**Comment by gino-m** [comment] 2021-06-01 20:16
@parulraheja98 Any idea why this might be happening?

Duplicate of #676.

**Closed by gino-m** 2021-06-01 20:16 UTC
Labels: type: bug
