### ISSUE TITLE
[Bug] - Some collected data don't show up in the side panel

### ISSUE THREAD

**Issue by rfontanarosa** [google/ground-platform#1451] opened 2024-01-17 12:48 UTC
- [ ] Take a photo
- [ ] Draw an area
- [ ] Drop a pin/Capture location

<img width="430" alt="Screenshot 2024-01-17 alle 13 39 47" src="https://github.com/google/ground-platform/assets/10047945/cc07120b-4487-4216-99e5-44c1664922fe">

**Comment by gino-m** [comment] 2024-01-17 14:53
Duplicate of #1279, filed #1456 to track photo bug. @rfontanarosa Please prefix bug descriptions with the screen on which they occur (for ex #1456).

**Closed** 2024-01-17 14:53 UTC
Labels: type: bug
