### ISSUE TITLE
[Create/edit survey] Allow organizers to add conditional tasks

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1478] opened 2024-02-07 19:10 UTC
Trigger:
![Image](https://github.com/google/ground-platform/assets/228050/b1dfea9e-5718-45d4-99ed-897ff96cb15d)

List selected values as comma-separated list in drop-down text:
![Image](https://github.com/google/ground-platform/assets/228050/223d32d0-e390-414e-918a-8b2597c418b7)

Truncate long names:
![Image](https://github.com/google/ground-platform/assets/228050/0752a700-b7b5-4794-89f9-d9664d99f803)

@rfontanarosa @vittorino FYI

**Comment by jcqli** [comment] 2024-02-09 15:07
@gino-m is this a duplicate of [#1955](https://github.com/google/ground-android/issues/1955)?

**Comment by gino-m** [comment] 2024-02-09 15:32
Yes! I was trying to call out top priority tasks, we can close that other one  as duplicate, thanks!

**Comment by jcqli** [comment] 2024-02-09 18:07
Since they're filed in separate repos let's use that that bug to track the android work to support this

**Comment by jcqli** [comment] 2024-02-14 17:14
@rfontanarosa From our sync earlier, assigning to you to tackle in next iteration

**Comment by sufyanAbbasi** [comment] 2024-02-15 06:09
I'm working on the problem from the Android side, and we should work towards agreeing on a JSON schema to encode "conditions" into the Task system. There are some interesting implementation questions that we should discuss:

1. Do we bind condition-related parameters to the Tasks that fulfill the condition or not? Should each Task not know about the conditions which are bound to it?
2. Should conditions have their own IDs which can be tracked across various Tasks?
3. Can a Task have multiple conditions to trigger it? If so, do we want to be able to configure "any" or "all" conditions for them? (Task A with option 1 or Task B with option 2 etc.)
4. Can conditional Tasks be reordered conditionally?
5. Can Tasks have conditional options?
6. Are conditions based on the `label` or `index` field of the options?
7. Can conditions be bound to the "other" option?
8. Can conditions be based on location or a bounding box?
9. Regular expression matching? May be useful for constructing easy string matching conditions

Here is a typical Tasks JSON:
```
"tasks": {
        "ePpIYkygrcm6cANlrhs3": {
          "required": false,
          "type": "multiple_choice",
          "label": "Pick an option, any option!",
          "index": 1,
          "cardinality": "select_one",
          "addLoiTask": false,
          "id": "ePpIYkygrcm6cANlrhs3",
          "hasOtherOption": true,
          "options": {
            "vknPVEALVkUvlOoyNiV9": {
              "code": "",
              "label": "a",
              "index": 0
            },
            "xkvErjPDwRjU47mkXXj9": {
              "index": 1,
              "code": "",
              "label": "b"
            },
            "ct8ZSVl4tdJkUKWJFOUK": {
              "index": 2,
              "code": "",
              "label": "c"
            }
          }
        },
        "wKK9LEHjo9oWeu1i71Ek": {
          "id": "wKK9LEHjo9oWeu1i71Ek",
          "addLoiTask": true,
          "label": "Pick your current location",
          "index": 0,
          "required": true,
          "type": "drop_pin"
        },
        "GqEBDoAoEnPbMmRbje5c": {
          "required": false,
          "id": "GqEBDoAoEnPbMmRbje5c",
          "hasOtherOption": true,
          "addLoiTask": false,
          "type": "multiple_choice",
          "label": "Pick an choice, any or all choices!",
          "options": {
            "Po2zyacw6FVFE6gaL8km": {
              "index": 1,
              "label": "y",
              "code": ""
            },
            "MFOdfshBZSieX5dddPfj": {
              "label": "x",
              "index": 0,
              "code": ""
            },
            "rVbIQmFIajZvnlSIl7n3": {
              "code": "",
              "index": 2,
              "label": "z"
            }
          },
          "index": 2,
          "cardinality": "select_multiple"
        }
      },
```

**Proposal**

1. Assume that tasks which show/hide based on a condition are in a set order (`index`), and that any conditions which apply to it must be defined on Tasks that come before it.
2. Define a `condition` schema which contains a property for "and" or "or" fulfillment and a list of `preconditions` which determine whether the Task should be shown or not.
3. Define a `precondition` schema which maps the Task ID of a previous task to the fulfillment condition based on the values of that task. Each `precondition` has a list of matchers/modes which define how to fulfill the condition (equality or comparisons). We can force preconditions to be match all for simplicity, which may require supporting regular expression matching if we want to easily allow for multiple string matches ("forest|desert|water").

Here's a proposal for the above schema:

```
task: {
  ...
  "id": string
  "conditions": {
    "matchAll": bool
    "preconditions": 
      "my-task-id": [
         {
            "value": number|string
            "check": "==" | "*=" ">" | "<" | ">=" | "<=" 
         },
        ...
       ]
    }
  }
}
```

Something like that?

**Comment by gino-m** [comment] 2024-02-15 20:51
@sufyanAbbasi Your assumptions are valid. I would propose a few simplifications to this FR that might make the impl simpler:

* Drop the requirement for "when adding LOI" conditions - since the CUJ is poorly defined here; it's not clear whether those answers would apply to the submission or the LOI anyway. We were proactively proposing this, but we can deprioritize it until it's needed.
* Only condition on "multiple choice" question answers for now. 

That said, we would still want our schema to be forward compatible should we add additional conditions or allow multiple conditions per task. So modifying your proposal a bit:

```
task: {
  ...
  "id": string
  "condition": {
    "matchType": "MATCH_ALL",
    "expressions": [
         {
            "expressionType": "ONE_OF_SELECTED",
            "taskId": "GqEBDoAoEnPbMmRbje5c",
            "optionIds": ["Po2zyacw6FVFE6gaL8km", "rVbIQmFIajZvnlSIl7n3"]
         }
      ]
      ...
```

For now there's only one `matchType` and `expressionType`, and `expressions` would have at most one item. `ONE_OF_SELECTED` mentions "selected" specifically because it can't be generically applied to any task type; the impl needs to know that the it's comparing a response id against the specified uuids, not just a string or number value. Not that `ALL_OF_SELECTED` is very unlikely to be useful, so probably will never happen.

@sufyanAbbasi wdyt?

**Comment by sufyanAbbasi** [comment] 2024-02-15 20:54
Perfect! And we can easily extend this to other match types in the future "VALUE_GREATER_THAN" etc., and we can trivially support "other" by making an "other" `optionId` if we choose to do so.

**Comment by gino-m** [comment] 2024-02-15 21:35
> Perfect! And we can easily extend this to other match types in the future "VALUE_GREATER_THAN" etc., and we can trivially support "other" by making an "other" `optionId` if we choose to do so.

Yes! Or even "VALUE_EXPRESSION" with some expression similar to the one you were proposing. Thanks

**Comment by sufyanAbbasi** [comment] 2024-02-16 02:39
Perhaps for consistency, expression types should be `ANY_OF_SELECTED` or `ALL_OF_SELECTED` to match `MATCH_ANY` and `MATCH_ALL`. Because `ONE_OF_SELECTED` implies that if the user selects both, the condition should not be fulfilled. It could also mean we could have another `expressionType` for `ONE_OF_SELECTED` which does exactly that.

**Comment by gino-m** [comment] 2024-02-16 16:34
> Perhaps for consistency, expression types should be `ANY_OF_SELECTED` or `ALL_OF_SELECTED` to match `MATCH_ANY` and `MATCH_ALL`. Because `ONE_OF_SELECTED` implies that if the user selects both, the condition should not be fulfilled. It could also mean we could have another `expressionType` for `ONE_OF_SELECTED` which does exactly that.

I doubt we'd need a true `ONE_OF_SELECTED`, but unambiguous naming if definitely better. +1!

**Closed** 2024-04-29 13:32 UTC
Labels: type: fr, web
