### ISSUE TITLE
Refactor create survey page

### ISSUE THREAD

**Issue by DaoyuT** [google/ground-platform#1043] opened 2023-02-02 19:58 UTC
Refactor CreateSurvey page & CreateJob page into NameSurvey component & NameJob component under CreateSurvey page.

We want the entire onboarding wizard to only have one page, it would swap the components in it instead of navigating to different pages.

**Comment by gino-m** [comment] 2023-02-02 20:07
Duplicate of #1009.

**Closed** 2023-02-22 00:34 UTC
Labels: type: feature request, web, priority: p0, feat: create survey
