### ISSUE TITLE
[Terra Bio] Rendering of option radio buttons is a bit tight

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#739] opened 2021-06-01 20:10 UTC
**Describe the bug**
Radio buttons in the web app seem to render a bit oddly—text spacing feels "off":

<img width="307" alt="Screen Shot 2021-06-01 at 4 09 08 PM" src="https://user-images.githubusercontent.com/11237600/120384238-e3d28c00-c2f3-11eb-8176-27f66fe5da6d.png">

**Comment by gino-m** [comment] 2021-06-01 20:14
Duplicate of #375. @gyarill could you PTAL?

**Closed** 2021-06-01 20:14 UTC
Labels: priority: p3, type: bug
